spring.application.name=file-integrity-monitor
monitoring.interval=20000
monitoring.file-path=monitored-files/application.log
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always