spring.application.name=file-integrity-monitor
monitoring.interval=30000
monitoring.file-path=monitored-files/application.log
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always